
/*
 * Copyright 2017 Martin Misiarz
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cz.babi.java.jhungryhamster.gui;

import static cz.babi.java.jhungryhamster.utils.Common.RESOURCE_BUNDLE;

import java.awt.Color;

/**
 *
 * @author babi
 */
public class RecipeBodyPanel extends javax.swing.JPanel {

    /** Creates new form RecipeBodyPanel */
    public RecipeBodyPanel() {
        initComponents();
    }
    
    public static void setTpMethod(String method) {
        tpMethod.setText(method);
    }
    
    public static void setTpIngredients(String ingredients) {
        tpIngredients.setText(ingredients);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRecipeBody = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        _lblMethod = new javax.swing.JLabel();
        _lblIngredients = new javax.swing.JLabel();
        spIngredients = new javax.swing.JScrollPane();
        tpIngredients = new javax.swing.JTextPane();
        spMethod = new javax.swing.JScrollPane();
        tpMethod = new javax.swing.JTextPane();

        setName("Form");

        pnlRecipeBody.setBorder(null);
        pnlRecipeBody.setName("pnlRecipeBody");
        pnlRecipeBody.setPreferredSize(new java.awt.Dimension(510, 40));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(null);
        jScrollPane1.setName("jScrollPane1");

        jPanel1.setBorder(null);
        jPanel1.setAutoscrolls(true);
        jPanel1.setName("jPanel1");

        _lblMethod.setText(RESOURCE_BUNDLE.getString("RecipeBodyPanel._lblMethod.text") + ":");
        _lblMethod.setMaximumSize(new java.awt.Dimension(85, 17));
        _lblMethod.setMinimumSize(new java.awt.Dimension(85, 17));
        _lblMethod.setName("_lblMethod");
        _lblMethod.setPreferredSize(new java.awt.Dimension(85, 17));

        _lblIngredients.setText(RESOURCE_BUNDLE.getString("RecipeBodyPanel._lblIngredients.text") + ":");
        _lblIngredients.setBorder(null);
        _lblIngredients.setMaximumSize(new java.awt.Dimension(85, 22));
        _lblIngredients.setMinimumSize(new java.awt.Dimension(85, 17));
        _lblIngredients.setName("_lblIngredients");
        _lblIngredients.setPreferredSize(new java.awt.Dimension(85, 17));

        spIngredients.setBorder(null);
        spIngredients.setViewportBorder(null);
        spIngredients.setName("spIngredients");

        tpIngredients.setBorder(null);
        tpIngredients.setEditable(false);
        tpIngredients.setToolTipText(RESOURCE_BUNDLE.getString("RecipeBodyPanel._lblIngredients.text"));
        tpIngredients.setName("tpIngredients");
        tpIngredients.setOpaque(false);
        spIngredients.setViewportView(tpIngredients);

        spMethod.setBorder(null);
        spMethod.setViewportBorder(null);
        spMethod.setName("spMethod");

        tpMethod.setBorder(null);
        tpMethod.setEditable(false);
        tpMethod.setToolTipText(RESOURCE_BUNDLE.getString("RecipeBodyPanel._lblMethod.text"));
        tpMethod.setName("tpMethod");
        tpMethod.setOpaque(false);
        spMethod.setViewportView(tpMethod);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_lblMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_lblIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spIngredients, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addComponent(spMethod, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_lblIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_lblMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout pnlRecipeBodyLayout = new javax.swing.GroupLayout(pnlRecipeBody);
        pnlRecipeBody.setLayout(pnlRecipeBodyLayout);
        pnlRecipeBodyLayout.setHorizontalGroup(
            pnlRecipeBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecipeBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlRecipeBodyLayout.setVerticalGroup(
            pnlRecipeBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecipeBodyLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRecipeBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRecipeBody, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _lblIngredients;
    private javax.swing.JLabel _lblMethod;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlRecipeBody;
    private javax.swing.JScrollPane spIngredients;
    private javax.swing.JScrollPane spMethod;
    private static javax.swing.JTextPane tpIngredients;
    private static javax.swing.JTextPane tpMethod;
    // End of variables declaration//GEN-END:variables

    /**
     * Potřeba z důvodu nastavení barvy pozadí pro jTextPane.
     */
    private static class MyTextPane extends javax.swing.JTextPane {
        public MyTextPane() {
            super();
            setOpaque(false);

            // this is needed if using Nimbus L&F - see http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6687960
            setBackground(new Color(0,0,0,0));
        }

        @Override
        protected void paintComponent(java.awt.Graphics g) {
            // set background green - but can draw image here too
            g.setColor(Color.red);
            g.fillRect(0, 0, getWidth(), getHeight());

            // uncomment the following to draw an image
            // Image res.img = ...;
            // g.drawImage(res.img, 0, 0, this);

            super.paintComponent(g);
        }
    }
}
