
/*
 * Copyright 2017 Martin Misiarz
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cz.babi.java.jhungryhamster.gui;

import cz.babi.java.jhungryhamster.data.Icons;
import cz.babi.java.jhungryhamster.data.CategoryIndenter;
import cz.babi.java.jhungryhamster.data.SearchWordSeparator;
import cz.babi.java.jhungryhamster.entity.ImageResolution;
import cz.babi.java.jhungryhamster.entity.MyTree;
import cz.babi.java.jhungryhamster.entity.Settings;
import cz.babi.java.jhungryhamster.utils.Common;
import org.pushingpixels.substance.api.SubstanceLookAndFeel;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ResourceBundle;

/**
 * Dialog umožňující změnu nastavení aplikace.
 * 
 * @author babi
 */
public class SettingsDialog extends javax.swing.JDialog {
    
    private static Settings settings = Settings.getInstance();

    /** Creates new form SettingsDialog */
    public SettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(Icons.HAMSTER_LOGO.getImage());
        
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {

            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResourceBundle bundle = Common.RESOURCE_BUNDLE;

        setTitle(bundle.getString("SettingsDialog.title"));

        btnClose = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        chbAutoLoadDatabase = new javax.swing.JCheckBox();
        chbShowRoot = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        chbShowWholeTree = new javax.swing.JCheckBox();
        chbSelectFirst = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cmbSearchSplitter = new javax.swing.JComboBox();
        txtSearchSplitter = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbTheme = new javax.swing.JComboBox();
        lblNote = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblResolution = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbCategoryIndention = new javax.swing.JComboBox();
        txtCategoryIndenterText = new javax.swing.JTextField();
        cmbResolution = new javax.swing.JComboBox();

        btnClose.setText(bundle.getString("SettingsDialog.btnClose.text"));
        btnClose.addActionListener(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnCloseActionPerformed(e);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jTabbedPane1.setName("jTabbedPane1");
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(470, 158));

        jPanel6.setName("jPanel6");

        chbAutoLoadDatabase.setText(bundle.getString("SettingsDialog.chbAutoLoadDatabase.text"));
        chbAutoLoadDatabase.setToolTipText(bundle.getString("SettingsDialog.chbAutoLoadDatabase.text"));
        chbAutoLoadDatabase.setName("chbAutoLoadDatabase");
        chbAutoLoadDatabase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbAutoLoadDatabaseItemStateChanged(evt);
            }
        });

        chbShowRoot.setText(bundle.getString("SettingsDialog.chbShowRoot.text"));
        chbShowRoot.setToolTipText(bundle.getString("SettingsDialog.chbShowRoot.text"));
        chbShowRoot.setName("chbShowRoot");
        chbShowRoot.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbShowRootItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbAutoLoadDatabase)
                    .addComponent(chbShowRoot))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chbAutoLoadDatabase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbShowRoot)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        chbAutoLoadDatabase.setSelected(settings.isAutoLoadDatabase());
        chbShowRoot.setSelected(settings.isShowRootElement());

        jTabbedPane1.addTab(bundle.getString("SettingsDialog.tab.main.text"), jPanel6);

        jPanel3.setName("jPanel3");

        chbShowWholeTree.setSelected(settings.isShowWholeTreeAfterSearch());
        chbShowWholeTree.setText(bundle.getString("SettingsDialog.chbShowWholeTree.text"));
        chbShowWholeTree.setToolTipText(bundle.getString("SettingsDialog.chbShowWholeTree.text"));
        chbShowWholeTree.setName("chbShowWholeTree");
        chbShowWholeTree.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbShowAllTreeItemStateChanged(evt);
            }
        });

        chbSelectFirst.setSelected(settings.isSelectFirstMatch());
        chbSelectFirst.setText(bundle.getString("SettingsDialog.chbSelectFirst.text"));
        chbSelectFirst.setToolTipText(bundle.getString("SettingsDialog.chbSelectFirst.text"));
        chbSelectFirst.setName("chbSelectFirst");
        chbSelectFirst.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbSelectFirstItemStateChanged(evt);
            }
        });

        jLabel1.setText(bundle.getString("SettingsDialog.lblSearchSplitter.text"));
        jLabel1.setName("jLabel1");

        jSeparator1.setName("jSeparator1");

        cmbSearchSplitter.setModel(new javax.swing.DefaultComboBoxModel(SearchWordSeparator.values()));
        cmbSearchSplitter.setSelectedItem(settings.getSearchSplitter());
        cmbSearchSplitter.setToolTipText(bundle.getString("SettingsDialog.cmbSearchSplitter.tooltip"));
        cmbSearchSplitter.setName("cmbSearchSplitter");
        cmbSearchSplitter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSearchSplitterItemStateChanged(evt);
            }
        });

        txtSearchSplitter.setText(settings.getUserSearchSplitter());
        txtSearchSplitter.setToolTipText(bundle.getString("SettingsDialog.txtSearchSplitter.tooltip"));
        txtSearchSplitter.setEnabled((settings.getSearchSplitter().equals(SearchWordSeparator.Custom) ? true : false));
        txtSearchSplitter.setName("txtSearchSplitter");
        txtSearchSplitter.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchSplitterCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(chbShowWholeTree)
                    .addComponent(chbSelectFirst)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSearchSplitter, 0, 124, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearchSplitter, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chbShowWholeTree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbSelectFirst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbSearchSplitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchSplitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(bundle.getString("SettingsDialog.tab.search.text"), jPanel3);

        jPanel5.setName("jPanel5");

        jLabel3.setText(bundle.getString("SettingsDialog.lblTheme.text"));
        jLabel3.setName("jLabel3");

        cmbTheme.setModel(new DefaultComboBoxModel(SubstanceLookAndFeel.getAllSkins().keySet().toArray()));
        cmbTheme.setSelectedItem(settings.getTheme());
        cmbTheme.setName("cmbTheme");
        cmbTheme.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbThemeItemStateChanged(evt);
            }
        });

        lblNote.setText(bundle.getString("SettingsDialog.lblNote.text"));
        lblNote.setName("lblNote");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(bundle.getString("SettingsDialog.tab.lookAndFeel.text"), jPanel5);

        jPanel4.setName("jPanel4");

        lblResolution.setText(bundle.getString("SettingsDialog.lblResolution.text"));
        lblResolution.setName("lblResolution");

        jLabel2.setText(bundle.getString("SettingsDialog.lblCategoryIndentation.text"));
        jLabel2.setName("jLabel2");

        cmbCategoryIndention.setModel(new javax.swing.DefaultComboBoxModel(CategoryIndenter.values()));
        cmbCategoryIndention.setSelectedItem(settings.getCategoryIndenter());
        cmbCategoryIndention.setToolTipText(bundle.getString("SettingsDialog.cmbCategoryIndention.tooltip"));
        cmbCategoryIndention.setName("cmbCategoryIndention");
        cmbCategoryIndention.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCategorySplitterItemStateChanged(evt);
            }
        });

        txtCategoryIndenterText.setText(settings.getUserCategoryJoiner());
        txtCategoryIndenterText.setToolTipText(bundle.getString("SettingsDialog.txtCategoryIndenterText.tooltip"));
        txtCategoryIndenterText.setEnabled((settings.getCategoryIndenter().equals(CategoryIndenter.Custom)) ? true : false);
        txtCategoryIndenterText.setName("txtCategoryIndenterText");
        txtCategoryIndenterText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCategorySplitterTextCaretUpdate(evt);
            }
        });

        cmbResolution.setModel(new DefaultComboBoxModel(ImageResolution.values()));
        cmbResolution.setToolTipText(bundle.getString("SettingsDialog.cmbResolution.tooltip"));
        cmbResolution.setName("cmbResolution");
        cmbResolution.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbResolutionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCategoryIndention, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblResolution))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbResolution, 0, 131, Short.MAX_VALUE)
                    .addComponent(txtCategoryIndenterText, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbResolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblResolution))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCategoryIndenterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cmbCategoryIndention, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        cmbResolution.setSelectedItem(settings.getImageResolution());

        jTabbedPane1.addTab(bundle.getString("SettingsDialog.tab.others.text"), jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void chbAutoLoadDatabaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbAutoLoadDatabaseItemStateChanged
        settings.setAutoLoadDatabase(chbAutoLoadDatabase.isSelected());
    }//GEN-LAST:event_chbAutoLoadDatabaseItemStateChanged

    private void chbShowRootItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbShowRootItemStateChanged
        settings.setShowRootElement(chbShowRoot.isSelected());
        if(chbShowRoot.isSelected()) {
            MyTree.getInstance().setRootVisible(true);
        } else {
            MyTree.getInstance().setRootVisible(false);
        }
    }//GEN-LAST:event_chbShowRootItemStateChanged

    private void cmbResolutionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbResolutionItemStateChanged
        settings.setImageResolution((ImageResolution)cmbResolution.getSelectedItem());
    }//GEN-LAST:event_cmbResolutionItemStateChanged

    private void txtCategorySplitterTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCategorySplitterTextCaretUpdate
        settings.setUserCategoryJoiner(txtCategoryIndenterText.getText());
        MyTree.createSortedCategories();
    }//GEN-LAST:event_txtCategorySplitterTextCaretUpdate

    private void cmbCategorySplitterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCategorySplitterItemStateChanged
        settings.setCategoryIndenter((CategoryIndenter)cmbCategoryIndention.getSelectedItem());
        if(settings.getCategoryIndenter().equals(CategoryIndenter.Custom)) {
            txtCategoryIndenterText.setEnabled(true);
            txtCategoryIndenterText.setText(settings.getUserCategoryJoiner());
        } else {
            txtCategoryIndenterText.setEnabled(false);
        }

        MyTree.createSortedCategories();
    }//GEN-LAST:event_cmbCategorySplitterItemStateChanged

    private void chbShowAllTreeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbShowAllTreeItemStateChanged
        settings.setShowWholeTreeAfterSearch(chbShowWholeTree.isSelected());
        if(!SearchPanel.getFilter().isEmpty()) MyTree.setFilterToModel(SearchPanel.getFilter(), true);
    }//GEN-LAST:event_chbShowAllTreeItemStateChanged

    private void chbSelectFirstItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbSelectFirstItemStateChanged
        settings.setSelectFirstMatch(chbSelectFirst.isSelected());
        if(!SearchPanel.getFilter().isEmpty()) MyTree.setFilterToModel(SearchPanel.getFilter(), true);
    }//GEN-LAST:event_chbSelectFirstItemStateChanged

    private void cmbSearchSplitterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSearchSplitterItemStateChanged
        settings.setSearchSplitter((SearchWordSeparator)cmbSearchSplitter.getSelectedItem());
        if(settings.getSearchSplitter().equals(SearchWordSeparator.Custom)) {
            txtSearchSplitter.setEnabled(true);
            txtSearchSplitter.setText(settings.getUserSearchSplitter());
        } else 
            txtSearchSplitter.setEnabled(false);

        if(!SearchPanel.getFilter().isEmpty()) MyTree.setFilterToModel(SearchPanel.getFilter(), true);
    }//GEN-LAST:event_cmbSearchSplitterItemStateChanged

    private void txtSearchSplitterCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchSplitterCaretUpdate
        settings.setUserSearchSplitter(txtSearchSplitter.getText());
        if(!SearchPanel.getFilter().isEmpty()) MyTree.setFilterToModel(SearchPanel.getFilter(), true);
    }//GEN-LAST:event_txtSearchSplitterCaretUpdate

    private void cmbThemeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbThemeItemStateChanged
        settings.setTheme(String.valueOf(cmbTheme.getSelectedItem()));
        //TODO: Apply style without restarting the app.
//        Common.useSubstanceLAF(settings.getTheme());
    }//GEN-LAST:event_cmbThemeItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JCheckBox chbAutoLoadDatabase;
    private javax.swing.JCheckBox chbSelectFirst;
    private javax.swing.JCheckBox chbShowWholeTree;
    private javax.swing.JCheckBox chbShowRoot;
    private javax.swing.JComboBox cmbCategoryIndention;
    private javax.swing.JComboBox cmbResolution;
    private javax.swing.JComboBox cmbSearchSplitter;
    private javax.swing.JComboBox cmbTheme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblResolution;
    private javax.swing.JTextField txtCategoryIndenterText;
    private javax.swing.JTextField txtSearchSplitter;
    // End of variables declaration//GEN-END:variables
}
