
/*
 * Copyright 2017 Martin Misiarz
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cz.babi.java.jhungryhamster.gui;

import cz.babi.java.jhungryhamster.data.Icons;
import cz.babi.java.jhungryhamster.utils.Common;

import javax.swing.ImageIcon;
import java.util.Date;

/**
 *
 * @author babi
 */
public class StatusPanel extends javax.swing.JPanel {
    
    /** Creates new form StatusPanel */
    public StatusPanel() {
        initComponents();
    }
    
    /** Prints message to status bar
     *
     * @param message text
     * @param time show timestamp before text. Use null for no timestamp.
     * @param icon show icon with text. Use null for no icon.
     */
    public void setStatusMessage(String message, Date time, ImageIcon icon) {
        lblStatusMessage.setIcon(icon);
        lblStatusMessage.setText("[" + 
                Common.convertDateToString(Common.DATEFORMAT_STATUS, time)
                + "] " + message);
    }
    
    /**
     * Metoda nastaví animační ikonu podle toho, co se právě v aplikaci děje.
     * @param icon 
     */
    public void setAnimationIcon(ImageIcon icon) {
        lblStatusAnimation.setIcon(icon);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatusMessage = new javax.swing.JLabel();
        lblStatusAnimation = new javax.swing.JLabel();

        setBorder(null);

        lblStatusMessage.setText("hello");
        lblStatusMessage.setFocusable(false);

        lblStatusAnimation.setIcon(Icons.TASK_IDLE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatusMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(180, 180, 180)
                .addComponent(lblStatusAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStatusAnimation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblStatusMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel lblStatusAnimation;
    private static javax.swing.JLabel lblStatusMessage;
    // End of variables declaration//GEN-END:variables

}
