
/*
 * Copyright 2017 Martin Misiarz
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cz.babi.java.jhungryhamster.gui;

import cz.babi.java.jhungryhamster.data.Icons;
import cz.babi.java.jhungryhamster.utils.Common;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ResourceBundle;

/**
 * Dialog O programu.
 * @author babi
 */
public class SupportProjectDialog extends javax.swing.JDialog {
    
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_CLOSE = 1;
    
    private static final String PAY_PAL_SUPPORT_URL = "https://www.paypal.com"
            + "/cgi-bin/webscr?cmd=_donations&business=dev%2emisiarz%40gmail%2"
            + "ecom&lc=CZ&item_name=jHungryHamster&currency_code=CZK&bn=PP%2d"
            + "DonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted";

    private static final Logger LOGGER = LoggerFactory.getLogger(SupportProjectDialog.class);

    /** Creates new form AboutApplicationDialog */
    public SupportProjectDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {

            public void actionPerformed(ActionEvent e) {
                doClose(RET_CLOSE);
            }
        });
        
        this.setLocationRelativeTo(null);
    }

    /** @return the return status of this dialog - one of RET_CLOSE or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblSupportTextFirst = new javax.swing.JLabel();
        lblSupportTextSecond = new javax.swing.JLabel();
        lblSupportTextThird = new javax.swing.JLabel();
        btnPayPalDonate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnShowDonators = new javax.swing.JButton();

        ResourceBundle bundle = Common.RESOURCE_BUNDLE;

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("SupportProjectDialog.title"));
        setName("Form");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText(bundle.getString("SupportProjectDialog.btnClose.text"));
        okButton.setToolTipText(bundle.getString("SupportProjectDialog.btnClose.tooltip"));
        okButton.setName("okButton");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 20));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("SupportProjectDialog.lblSupport.text"));
        jLabel1.setName("jLabel1");

        lblSupportTextFirst.setText(bundle.getString("SupportProjectDialog.lblSupportTextFirst.text"));
        lblSupportTextFirst.setName("lblSupportTextFirst");

        lblSupportTextSecond.setText(bundle.getString("SupportProjectDialog.lblSupportTextSecond.text"));
        lblSupportTextSecond.setName("lblSupportTextSecond");

        lblSupportTextThird.setText(bundle.getString("SupportProjectDialog.lblSupportTextThird.text"));
        lblSupportTextThird.setName("lblSupportTextThird");

        btnPayPalDonate.setIcon(Icons.PAY_PAL_DONATE);
        btnPayPalDonate.setToolTipText(bundle.getString("SupportProjectDialog.btnPayPalDonate.tooltip"));
        btnPayPalDonate.setName("btnPayPalDonate");
        btnPayPalDonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayPalDonateActionPerformed(evt);
            }
        });

        jLabel2.setText(bundle.getString("SupportProjectDialog.lblSupportBankAccount.text"));
        jLabel2.setName("jLabel2");

        jLabel3.setText(bundle.getString("SupportProjectDialog.lblSupportBankAccountPayPal.text"));
        jLabel3.setName("jLabel3");

        jLabel4.setText(bundle.getString("SupportProjectDialog.lblSupportBankAccountNumber.text"));
        jLabel4.setName("jLabel4");

        jLabel5.setText(bundle.getString("SupportProjectDialog.lblSupportThanks.text"));
        jLabel5.setName("jLabel5");

        btnShowDonators.setText(bundle.getString("SupportProjectDialog.btnShowDonors.text"));
        btnShowDonators.setToolTipText(bundle.getString("SupportProjectDialog.btnShowDonors.tooltip"));
        btnShowDonators.setName("btnShowDonators");
        btnShowDonators.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDonatorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSupportTextFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnShowDonators)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSupportTextSecond, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPayPalDonate)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)))
                            .addComponent(lblSupportTextThird, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblSupportTextFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSupportTextSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSupportTextThird, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnPayPalDonate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(btnShowDonators))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_CLOSE);
    }//GEN-LAST:event_okButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CLOSE);
    }//GEN-LAST:event_closeDialog

    private void btnPayPalDonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayPalDonateActionPerformed
        if(Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URI(PAY_PAL_SUPPORT_URL));
            } catch(URISyntaxException urise) {
                LOGGER.error("An error occurred while parsing URI.", urise);
            } catch(IOException ioe) {
                LOGGER.error("An error occurred while opening the URL.", ioe);
            }
        }
    }//GEN-LAST:event_btnPayPalDonateActionPerformed

    private void btnShowDonatorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDonatorsActionPerformed
        DonatorsDialog donatorDialog = new DonatorsDialog(null, true);
        donatorDialog.setVisible(true);
    }//GEN-LAST:event_btnShowDonatorsActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPayPalDonate;
    private javax.swing.JButton btnShowDonators;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblSupportTextFirst;
    private javax.swing.JLabel lblSupportTextSecond;
    private javax.swing.JLabel lblSupportTextThird;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CLOSE;
}
